{
 "title": "Magento COUNT",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "PRODUCTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_products_count_total{} ",
     "legendFormat": "Products"
    }
   ]
  },
  {
   "title": "CATEGORIES PRODUCTS",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_catalog_category_count_total{store_code=\"default\",status=\"enabled\",menu_status=\"enabled\"}",
     "legendFormat": "Categories enable"
    },
    {
     "expr": "magento_catalog_category_count_total{store_code=\"default\",status=\"disabled\",menu_status=\"disabled\"}",
     "legendFormat": "Categories disable"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "COUNT COSTUMER",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_customer_count_total{store_code=\"default\"}"
    }
   ]
  },
  {
   "title": "ORDERS COUNT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_orders_count_total{state=\"new\",store_code=\"default\"}",
     "legendFormat": "Orders count New"
    },
    {
     "expr": "magento_orders_count_total{state=\"complete\",store_code=\"default\"}",
     "legendFormat": "Orders count complete"
    },
    {
     "expr": "magento_orders_count_total{state=\"closed\",store_code=\"default\"}",
     "legendFormat": "Orders count closed"
    },
    {
     "expr": "magento_orders_count_total{state=\"canceled\",store_code=\"default\"}",
     "legendFormat": "Orders count canceled"
    }
   ]
  },
  {
   "title": "ORDERS AMOUNT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_orders_amount_total{state=\"new\",store_code=\"default\"}",
     "legendFormat": "New orders amount"
    },
    {
     "expr": "magento_orders_amount_total{state=\"complete\",store_code=\"default\"}",
     "legendFormat": "Complete orders amount "
    },
    {
     "expr": "magento_orders_amount_total{state=\"closed\",store_code=\"default\"}",
     "legendFormat": "Closed orders amount"
    },
    {
     "expr": "magento_orders_amount_total{state=\"canceled\",store_code=\"default\"}",
     "legendFormat": "Canceled orders amount"
    }
   ]
  },
  {
   "title": "ORDERS ITENS",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_orders_items_count_total{status=\"Comprado\",store_code=\"default\"}",
     "legendFormat": "Itens comprados"
    },
    {
     "expr": "magento_orders_items_count_total{status=\"Faturado\",store_code=\"default\"}",
     "legendFormat": "Itens faturados"
    },
    {
     "expr": "magento_orders_items_count_total{status=\"Enviado\",store_code=\"default\"}",
     "legendFormat": "Itens enviados"
    },
    {
     "expr": "magento_orders_items_count_total{status=\"Cancelado\",store_code=\"default\"}",
     "legendFormat": "Itens cancelados"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "DESIGN CONFIG GRID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Design Config Grid\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Design Config Grid\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Design Config Grid\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "COSTUMER GRID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Customer Grid\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Customer Grid\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Customer Grid\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "CATEGORY PRODUCTS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Category Products\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Category Products\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Category Products\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "PRODUCT CATEGORIES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Product Categories\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Product Categories\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Product Categories\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "CATALOG RULE PRODUCT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Catalog Rule Product\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Catalog Rule Product\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Catalog Rule Product\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "PRODUCT EAV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Product EAV\",status=\"valid\"} ",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Product EAV\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Product EAV\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "PRODUCT PRICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Product Price\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Product Price\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Product Price\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "CATALOG PRODUCT RULE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Catalog Product Rule\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Catalog Product Rule\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Catalog Product Rule\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "STOCK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Stock\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Stock\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Stock\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "PRODUCT/TARGET RULE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Product/Target Rule\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Product/Target Rule\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Product/Target Rule\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "TARGET RULE/PRODUCT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Target Rule/Product\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Target Rule/Product\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Target Rule/Product\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "CATALOG SEARCH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"\",title=\"Catalog Search\",status=\"working\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"\",title=\"Catalog Search\",status=\"working\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"\",title=\"Catalog Search\",status=\"working\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "SALES RULES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Sales Rule\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Sales Rule\",status=\"valid\"} ",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Sales Rule\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "UNIRGY VENDOR - PRODUCT ASSOCIATIONS INDEXER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Unirgy Vendor-Product Associations Indexer\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Unirgy Vendor-Product Associations Indexer\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Unirgy Vendor-Product Associations Indexer\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "UNIRGY PRODUCT - VENDOR ASSOCIATIONS INDEXER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Unirgy Product-Vendor Associations Indexer\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Unirgy Product-Vendor Associations Indexer\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Unirgy Product-Vendor Associations Indexer\",status=\"valid\"}",
     "legendFormat": "LAST CAÇÇ SECONDS"
    }
   ]
  },
  {
   "title": "UNIRGY VENDOR SHIP - TO LOCATION LIMIT VENDOR INDEXER INDEXER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Unirgy Vendor Ship-To Location Limit Vendor Indexer\",status=\"valid\"} ",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Unirgy Vendor Ship-To Location Limit Vendor Indexer\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Unirgy Vendor Ship-To Location Limit Vendor Indexer\",status=\"valid\"}",
     "legendFormat": "LAST CALL SECONDS"
    }
   ]
  },
  {
   "title": "UNIRGY VENDOR SHIP - TO LOCATION LIMIT PRODUCT INDEXER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "magento_indexer_backlog_count_total{isValid=\"1\",title=\"Unirgy Vendor Ship-To Location Limit Product Indexer\",status=\"valid\"}",
     "legendFormat": "BACKLOG"
    },
    {
     "expr": "magento_indexer_changelog_count_total{isValid=\"1\",title=\"Unirgy Vendor Ship-To Location Limit Product Indexer\",status=\"valid\"}",
     "legendFormat": "CHANGELOG"
    },
    {
     "expr": "magento_indexer_last_call_seconds_count{isValid=\"1\",title=\"Unirgy Vendor Ship-To Location Limit Product Indexer\",status=\"valid\"}",
     "legendFormat": "LASCT CALL SECONDS"
    }
   ]
  }
 ]
}